# NumPy
NumPy is a Linear Algebra Library in Python and it is the holy grail and the main building block of Data Science using Python. Almost all the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

It is bound to several C libraries which makes NumPy one of the fastest libraries in Python.

We will learn the basics of NumPy, to get started we need to install it!

## Installation Instructions

**It is highly recommended you install Python using the Anaconda distribution to make sure all underlying dependencies (such as Linear Algebra libraries) all sync up with the use of a conda install. If you don't have Anaconda, install NumPy by going to your terminal or command prompt and type:**
    
    !pip install numpy
    conda install numpy
    


## Using NumPy

Once you've installed NumPy you can import it as a library:

In [1]:
import numpy as np

Numpy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of Numpy: vectors,arrays,matrices, and number generation.

# Numpy Arrays

Numpy arrays essentially of two types: vectors and matrices. Vectors are strictly 1-D arrays and matrices are 2-D (Note: A matrix can still have only one row or one column).

The following cells explain on creation of NumPy arrays.

## Creating NumPy Arrays

### From a Python List

An array can be created by directly converting a list or list of lists:

In [2]:
import numpy as np

In [3]:
  arr1 = np.array([])   # create an empty array
  arr1

array([], dtype=float64)

In [5]:
my_list = [1,2,3,4,5]
print(my_list)
print(type(my_list))

[1, 2, 3, 4, 5]
<class 'list'>


In [6]:
a=np.array(my_list)

In [7]:
a

array([1, 2, 3, 4, 5])

In [9]:
type(a)   # ndarray is number dimension array

numpy.ndarray

In [10]:
a.ndim  # number of dimensions in the array

1

In [11]:
a.size  # size of an array is the no. of items

5

In [12]:
a.shape # shape of array

(5,)

#### Arrays can be of n dimensions.

In [13]:
my_matrix = [[1,2,3,4],[5,6,7,8],[9,10,11,12]] # list of lists
my_matrix

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

In [14]:
b=np.array(my_matrix) # generates a 2-d array
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [15]:
# Array summary
print('The Dimension of array',b.ndim) # dimensions of given array

The Dimension of array 2


In [16]:
print('The size of array:',b.size) # Number of elements in array

The size of array: 12


In [17]:
print('The datatype of element:',b.dtype) # Datatype of elements in array

The datatype of element: int64


In [18]:
print('The type of structure:',type(b))

The type of structure: <class 'numpy.ndarray'>


In [19]:
print('The shape:',b.shape)

The shape: (3, 4)


In [20]:
b.shape

(3, 4)

In [21]:
arr1= np.array([[[1,2,3],[4,5,6]], [[7,8,9],[10,11,12]]])
arr1

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [22]:
arr1.shape #2 blocks (outermost level) ,Each block has 2 rows ,Each row has 3 elements (columns)

(2, 2, 3)

In [23]:
arr1[0][1][2]

np.int64(6)

In [24]:
arr2=np.array(["this",'is']) 

In [25]:
arr2

array(['this', 'is'], dtype='<U4')

In [26]:
np.mean([1,2,3,4])

np.float64(2.5)

## Built-in Methods

There are lots of built-in ways to generate Arrays

### Reshape function

In [27]:
arr1.shape

(2, 2, 3)

In [28]:
arr1

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [29]:
arr2=arr1.reshape(2,3,2)  # reshape function takes the new shape as its argument

In [30]:
arr2

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [31]:
arr2.reshape(-1) #  it flattens the array into a 1D array.

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

### arange

Return evenly spaced values within a given interval.

In [32]:
np.arange(15) # end; default start at 0

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [33]:
np.arange(2,15) # start, end and step

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [34]:
np.arange(0,10,2) # start end and step

array([0, 2, 4, 6, 8])

### zeros and ones

Generate arrays of zeros or ones

In [35]:
import numpy as np

In [36]:
np.zeros(3) # Generates array in 1 dimension with all elements 0

array([0., 0., 0.])

In [37]:
np.zeros((5,5))  # Generates array in 2 diemnsions with all elements 0

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [38]:
np.ones(3) # Generates array of 1 dimension where all elements are 1

array([1., 1., 1.])

In [39]:
np.ones((3,3,2)) # Generates array of 3 dimensions where all elements are 1

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

### linspace
Return evenly spaced numbers over a specified interval.

In [40]:
import numpy as np

In [41]:
np.linspace(1,10,10)  # default 50 observations
# both the start and end are included in the array

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [42]:
np.linspace(5,25,10,retstep=True)  # equally spaced 10 values
#If you set retstep=True, NumPy returns a tuple:The array of values, and The step size between them.

(array([ 5.        ,  7.22222222,  9.44444444, 11.66666667, 13.88888889,
        16.11111111, 18.33333333, 20.55555556, 22.77777778, 25.        ]),
 np.float64(2.2222222222222223))

In [43]:
# retstep ~ return step computed by linspace

In [44]:
np.linspace(0,25, retstep=True) # Start # end (Here end is included) and default elements are 50

(array([ 0.        ,  0.51020408,  1.02040816,  1.53061224,  2.04081633,
         2.55102041,  3.06122449,  3.57142857,  4.08163265,  4.59183673,
         5.10204082,  5.6122449 ,  6.12244898,  6.63265306,  7.14285714,
         7.65306122,  8.16326531,  8.67346939,  9.18367347,  9.69387755,
        10.20408163, 10.71428571, 11.2244898 , 11.73469388, 12.24489796,
        12.75510204, 13.26530612, 13.7755102 , 14.28571429, 14.79591837,
        15.30612245, 15.81632653, 16.32653061, 16.83673469, 17.34693878,
        17.85714286, 18.36734694, 18.87755102, 19.3877551 , 19.89795918,
        20.40816327, 20.91836735, 21.42857143, 21.93877551, 22.44897959,
        22.95918367, 23.46938776, 23.97959184, 24.48979592, 25.        ]),
 np.float64(0.5102040816326531))

In [45]:
np.linspace(0,200,10) # default retstep=False

array([  0.        ,  22.22222222,  44.44444444,  66.66666667,
        88.88888889, 111.11111111, 133.33333333, 155.55555556,
       177.77777778, 200.        ])

In [46]:
np.linspace(0,200,10,retstep=True)

(array([  0.        ,  22.22222222,  44.44444444,  66.66666667,
         88.88888889, 111.11111111, 133.33333333, 155.55555556,
        177.77777778, 200.        ]),
 np.float64(22.22222222222222))

### eye

Creates an identity matrix

In [47]:
np.eye(3)   # generates 2d array of (5,5)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [48]:
# Create an eye from a zeros array

### Broadcasting in an array

In [49]:
big_one=np.ones((3,4))
print(big_one)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [50]:
big_one.dtype

dtype('float64')

In [51]:
big_one * 3

array([[3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.]])

#### The ability to access each and every element of an array is known as Broadcasting.

In [52]:
bigger_one=big_one*6 - 2
bigger_one

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [53]:
big_one

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [54]:
bigger=np.array(big_one*3 - 0.4, dtype='int')
print(bigger)

[[2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]]


In [55]:
bigger.dtype

dtype('int64')

In [56]:
type(bigger)

numpy.ndarray

In [57]:
bigger.shape

(3, 4)

In [58]:
bigger/bigger

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [59]:
arr=np.arange(4)

In [60]:
arr

array([0, 1, 2, 3])

In [61]:
arr + arr

array([0, 2, 4, 6])

In [62]:
arr

array([0, 1, 2, 3])

In [63]:
arr  **arr # power

array([ 1,  1,  4, 27])

### Use of Copy function

In [71]:
arr1=np.arange(0,20)

In [72]:
arr2 = arr1 # not recommended
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [73]:
arr1[1]=100

In [74]:
arr1

array([  0, 100,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19])

In [75]:

arr2

array([  0, 100,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19])

In [76]:
array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

NameError: name 'array' is not defined

In [77]:
arr3 = arr1.copy() # generate a copy / creates a backup

In [78]:
arr3[10:] = 100
arr3

array([  0, 100,   2,   3,   4,   5,   6,   7,   8,   9, 100, 100, 100,
       100, 100, 100, 100, 100, 100, 100])

In [79]:
arr1  # copy function retains the original. copy creates a backup array.

array([  0, 100,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19])

In [80]:
 def fibo(n):
  l1=[0,1]
  a=0
  b=1
  for i in range(n-2):
    c=a+b
    print(c)
    a=b
    b=c
  return l1

In [81]:
fibo(15)

1
2
3
5
8
13
21
34
55
89
144
233
377


[0, 1]

## Random number generation

Numpy also has lots of ways to create random number arrays:

### rand
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [82]:
import numpy as np

In [83]:
np.random.rand()

0.22352232129213212

In [84]:
np.random.rand(10) # rand gives values between 0 and 1

array([0.40178686, 0.85247364, 0.62418399, 0.07490907, 0.61862376,
       0.40333684, 0.46982183, 0.91667009, 0.70946008, 0.08320669])

In [85]:
np.random.rand(5,2)

array([[0.65526933, 0.96296156],
       [0.52281692, 0.7453269 ],
       [0.39013979, 0.80515546],
       [0.43612141, 0.40210705],
       [0.22227516, 0.5356328 ]])

In [86]:
# Creating array from uniform distribution

new_arr=np.random.rand(5,3)
# 2 dimensional array of shape (5,3)

In [87]:
new_arr

array([[0.30801273, 0.64410346, 0.35217725],
       [0.66383819, 0.49860686, 0.15938541],
       [0.6775829 , 0.9176959 , 0.32853223],
       [0.83565376, 0.79660174, 0.71489609],
       [0.99175237, 0.17186973, 0.06950527]])

In [88]:
np.random.rand(3,3)

array([[0.01029056, 0.1331087 , 0.51077803],
       [0.94933128, 0.95579473, 0.87484623],
       [0.78289472, 0.25321153, 0.35508099]])

### randn

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [89]:
# For randn, random numbbers generated will be in approximately -3 to +3 range.

In [90]:
arr1=np.random.randn(50)  # 50 observations from std normal distribution
arr1

array([-0.72646761, -0.55602729,  0.04563876, -1.52537651,  0.06457237,
        0.12051478,  0.45918474,  0.93963897, -0.86189408,  1.2783216 ,
       -0.18694216, -1.17623423,  0.06934355,  0.23772383,  1.14497453,
        0.85877021, -0.71666009,  1.01689553, -1.67239573,  0.31113849,
       -0.29437518, -0.54815855,  1.18420806, -0.91294754, -0.00907561,
        2.38615271,  0.17662957,  1.28058161,  0.02531102, -1.29417884,
       -0.59264786, -0.62360985,  0.81746022,  1.3182709 , -0.35173082,
       -0.37154051,  0.35567417, -0.52581969, -0.07856898, -1.17303187,
       -1.35715311,  0.34985463, -0.09515844,  1.11937976, -1.33706881,
        1.49664906,  0.66123257,  0.96559767, -0.13330317,  0.21203748])

In [91]:
np.mean(arr1)

np.float64(0.03550780549447213)

In [92]:
np.median(arr1)

np.float64(0.035474891378385956)

In [93]:
np.std(arr1)

np.float64(0.8955970525598136)

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [94]:
np.random.randint(1,100)
# third argument is no. of values. default =1 value

84

In [96]:
np.random.randint(1,100,20)

array([ 7, 59, 32, 60, 84, 94, 68, 58, 38,  1, 54, 49, 73, 63,  3, 36,  2,
       99, 66, 47], dtype=int32)

In [97]:
np.random.randint(40,60,50) # generating 50 values between

array([41, 58, 52, 51, 55, 48, 51, 52, 57, 53, 58, 45, 40, 47, 57, 43, 58,
       59, 46, 51, 54, 42, 46, 46, 40, 53, 55, 45, 49, 58, 45, 58, 57, 56,
       56, 46, 45, 45, 53, 56, 56, 43, 58, 46, 50, 52, 47, 55, 41, 45],
      dtype=int32)

## Array Attributes and Methods

Let's discuss some useful attributes and methods or an array:

In [98]:
arr = np.arange(20)
ranarr = np.random.randint(0,100,10)

In [99]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [100]:
ranarr

array([69, 45, 40, 40, 76, 34, 10, 75, 92, 50], dtype=int32)

### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [ ]:
arr2=np.random.randint(1,100,20)

In [ ]:
arr2

In [ ]:
arr2.max()

In [ ]:
arr2.min()

In [ ]:
arr2.argmax()


In [ ]:
arr2.argmin()

In [ ]:
arr.max()

In [ ]:
ranarr.argmax() ## Index location of highest element

In [ ]:
ranarr.min() # Gives the lowest element of array

In [ ]:
ranarr.argmin() # Index location of lowest element

In [ ]:
ran2=ranarr.reshape(2,5)

In [ ]:
ran2

In [ ]:
ran2.argmax()

In [ ]:
ran2.max()

# Happy Learning!